import { describe, expect, it } from 'vitest'
import { day7pt1, day7pt2 } from '../day7.ts'

describe('day 7 examples should pass', () => {
  const example = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`.split('\n')

  it('should pass pt1', () => {
    const result = day7pt1(example)
    expect(result).toBe(21)
  })
  it('should pass pt2', () => {
    const result = day7pt2(example)
    expect(result).toBe(40)
  })
})
